# Site settings
title: Jyoti Bose
description: My Work Life  
keywords: AI-ML,Animation,Equity,Learning
author: Jyoti Bose
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
